//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_websach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
            this.Reviews = new HashSet<Review>();
        }
        [Display(Name = "Mã khách hàng")] //đặt lại tên cho thuộc tính
        public int CustomerID { get; set; }


        [Display(Name = "Tên khách hàng")]
        [Required(ErrorMessage = "{0} không được để trống !")] //kiểm tra rỗng 
        [StringLength(30, ErrorMessage = "Không quá 30 ký tự")] //kiểm tra chiều dài tối đa của đầu vào
        [MinLength(5)]
        public string CustomerName { get; set; }


        [Display(Name = "Email")]
        [Required(ErrorMessage = "{0} không được để trống !")] //kiểm tra rỗng
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "{0} không hợp lệ ")]
        public string Email { get; set; }


        [Display(Name = "Số điện thoại")]
        [Required(ErrorMessage = "{0} không được để trống !")] //kiểm tra rỗng
        [StringLength(11, ErrorMessage = "Không quá 11 ký tự")] 
        [MinLength(9)]
        public string PhoneNumber { get; set; }


        [Display(Name = "Mật khẩu")]
        [Required(ErrorMessage = "{0} không được để trống !")] //kiểm tra rỗng
        [MinLength(8, ErrorMessage = "Mật khẩu phải tối thiểu là 8 ký tự")]
        public string MatKhau { get; set; }


        [Display(Name = "Ngày sinh")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgaySinh { get; set; }



        [Display(Name = "Địa chỉ")]
        [Required(ErrorMessage = "{0} không được để trống !")] //kiểm tra rỗng
        [StringLength(50, ErrorMessage = "Không quá 50 ký tự")] //kiểm tra chiều dài tối đa của đầu vào
        public string DiaChi { get; set; }



    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
